In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In this notebook we clean and transform the data, so it is easy to use for the modelling part.
The dataset used in this notebook is data concerning civil incidents with the intervention of Greek fire services between years 2014-2024. Out of this data, only the forest fires events were taken into consideration. A brief overview of the actions taken in this notebook:

- data concatenation
- final data translation
- dropping irrelevant columns
- dropping rows with many missing values
- selecting only forest fire events
- encoding non-numerical columns
- feature engineering: creating several new columns

The data source: 
https://www.fireservice.gr/en_US/synola-dedomenon  - website in Greek

To obtain a partial translation of the datasets we used ChatGPT and Copilot resources.

In [8]:
import os

df1 = pd.read_csv(os.path.join('..', 'data', 'partially_translated', 'Translated_Astika_Symvanta_2014.csv'))
df2 = pd.read_csv(os.path.join('..', 'data', 'partially_translated', 'Translated_Astika_Symvanta_2015.csv'))
df3 = pd.read_csv(os.path.join('..', 'data', 'partially_translated', 'Translated_Astika_Symvanta_2016.csv'))
df4 = pd.read_csv(os.path.join('..', 'data', 'partially_translated', 'Translated_Astika_Symvanta_2017.csv'))
df5 = pd.read_csv(os.path.join('..', 'data', 'partially_translated', 'Translated_Astika_Symvanta_2018.csv'))
df6 = pd.read_csv(os.path.join('..', 'data', 'partially_translated', 'Translated_Astika_Symvanta_2019.csv'))
df7 = pd.read_csv(os.path.join('..', 'data', 'partially_translated', 'Translated_Astika_Symvanta_2020.csv'))
df8 = pd.read_csv(os.path.join('..', 'data', 'partially_translated', 'Translated_Astika_Symvanta_2021.csv'))
df9 = pd.read_csv(os.path.join('..', 'data', 'partially_translated', 'Translated_Astika_Symvanta_2022.csv'))
df10 = pd.read_csv(os.path.join('..', 'data', 'partially_translated', 'Translated_Astika_Symvanta_2023.csv'))
df11 = pd.read_csv(os.path.join('..', 'data', 'partially_translated', 'Translated_Astika_Symvanta_2024.csv'))

In [9]:
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11])

In [10]:
df

,Α/Α Εγγραφής,Υπηρεσία,Νομός,Είδος Συμβάντος,Ημερ. Έναρξης Συμβάντος,Ώρα Έναρξης,Ημερ. Κατάσβεσης,Ώρα Κατάσβεσης,Δήμος,Χωριό,...,Σύνολο Πυρ. Δυνάμεων (σε άνδρες και γυναίκες),Σύνολο Πυροσβεστικών Πλοιαρίων,Τύπος Ατυχήματος,Αριθμός εμπλεκομένων ανά τύπο ατυχήματος,Τραυματίες,Θάνατοι,Καταστροφές,Εγκαύματα,Σύνολο Πυροσβ. Πλοιαρίων,Αριθμός εμπλεκομένων ανά τύπο
0,1165953,Π.Υ. Κ/Α ΑΘΗΝΩΝ - ΕΛΕΥΘ. ΒΕΝΙΖΕΛΟΣ,ΑΤΤΙΚΗΣ,ΠΥΡΚΑΓΙΑ,2014-01-04,19:36,NaN,NaN,Δ. ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ,NaN,...,3.0,NaN,NaN,1.0,0,0,0,0,NaN,NaN
1,1107604,Π.Υ. Κ/Α ΑΘΗΝΩΝ - ΕΛΕΥΘ. ΒΕΝΙΖΕΛΟΣ,ΑΤΤΙΚΗΣ,ΠΑΡΟΧΗ ΒΟΗΘΕΙΑΣ,2014-01-06,12:15,NaN,NaN,Δ. ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ,NaN,...,7.0,NaN,ΑΤΥΧΗΜΑ,2.0,2,0,0,0,NaN,NaN
2,1109979,Π.Υ. Κ/Α ΑΘΗΝΩΝ - ΕΛΕΥΘ. ΒΕΝΙΖΕΛΟΣ,ΑΤΤΙΚΗΣ,ΠΥΡΚΑΓΙΑ,2014-01-09,20:35,NaN,NaN,Δ. ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ,NaN,...,5.0,NaN,NaN,1.0,0,0,0,0,NaN,NaN
3,1107605,Π.Υ. Κ/Α ΑΘΗΝΩΝ - ΕΛΕΥΘ. ΒΕΝΙΖΕΛΟΣ,ΑΤΤΙΚΗΣ,ΠΥΡΚΑΓΙΑ,2014-01-18,13:47,NaN,NaN,Δ. ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ,NaN,...,4.0,NaN,NaN,1.0,0,0,0,0,NaN,NaN
4,1107607,Π.Υ. Κ/Α ΑΘΗΝΩΝ - ΕΛΕΥΘ. ΒΕΝΙΖΕΛΟΣ,ΑΤΤΙΚΗΣ,ΠΥΡΚΑΓΙΑ,2014-01-18,14:06,NaN,NaN,Δ. ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ,NaN,...,4.0,NaN,NaN,1.0,0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65742,2014747,Π.Κ. ΕΛΑΤΙΩΝ,ΖΑΚΥΝΘΟΥ,Assistance Provision Report,2024-09-29,11:15,NaN,NaN,Δ. ΖΑΚΥΝΘΟΥ,ΒΟΛΙΜΕΣ,...,4.0,NaN,NaN,NaN,0,0,0,0,0.0,1.0
65743,2021135,Π.Κ. ΕΛΑΤΙΩΝ,ΖΑΚΥΝΘΟΥ,Fire Report,2024-10-15,13:31,NaN,NaN,Δ. ΖΑΚΥΝΘΟΥ,ΒΟΛΙΜΕΣ,...,6.0,NaN,NaN,NaN,0,0,0,0,0.0,1.0
65744,2023818,Π.Κ. ΕΛΑΤΙΩΝ,ΖΑΚΥΝΘΟΥ,Assistance Provision Report,2024-10-21,08:41,NaN,NaN,Δ. ΖΑΚΥΝΘΟΥ,ΒΟΛΙΜΕΣ,...,2.0,NaN,ΔΙΑΣΩΣΗ,NaN,0,0,0,0,0.0,2.0
65745,2037109,Π.Κ. ΕΛΑΤΙΩΝ,ΖΑΚΥΝΘΟΥ,Assistance Provision Report,2024-12-09,10:45,NaN,NaN,Δ. ΖΑΚΥΝΘΟΥ,NaN,...,3.0,NaN,NaN,NaN,0,0,0,0,0.0,1.0
65746,2007003,Π.Υ. Α/Λ ΖΑΚΥΝΘΟΥ,ΖΑΚΥΝΘΟΥ,Assistance Provision Report,2024-09-02,19:00,NaN,NaN,Δ. ΖΑΚΥΝΘΟΥ,ΖΑΚΥΝΘΟΣ,...,2.0,NaN,NaN,NaN,0,0,0,0,0.0,1.0

In [16]:
df.columns

Index(['Α/Α Εγγραφής', 'Υπηρεσία', 'Νομός', 'Είδος Συμβάντος',
       'Ημερ. Έναρξης Συμβάντος', 'Ώρα Έναρξης', 'Ημερ. Κατάσβεσης',
       'Ώρα Κατάσβεσης', 'Δήμος', 'Χωριό', 'Περιγραφή Χώρου',
       'Χαρακτηρισμός Συμβάντος', 'Σύνολο Πυρ. Οχημάτων',
       'Σύνολο Πυρ. Δυνάμεων (σε άνδρες και γυναίκες)',
       'Σύνολο Πυροσβεστικών Πλοιαρίων', 'Τύπος Ατυχήματος',
       'Αριθμός εμπλεκομένων ανά τύπο ατυχήματος', 'Τραυματίες', 'Θάνατοι',
       'Καταστροφές', 'Εγκαύματα', 'Σύνολο Πυροσβ. Πλοιαρίων',
       'Αριθμός εμπλεκομένων   ανά τύπο '],
      dtype='object')

In [17]:
# rename columns
df.rename(columns={
    'Α/Α Εγγραφής': 'Record ID',
    'Υπηρεσία': 'Service',
    'Νομός': 'Region',
    'Είδος Συμβάντος': 'Incident Type',
    'Ημερ. Έναρξης Συμβάντος': 'Incident Start Date',
    'Ώρα Έναρξης': 'Start Time',
    'Ημερ. Κατάσβεσης': 'Extinguishing Date',
    'Ώρα Κατάσβεσης': 'Extinguishing Time',
    'Δήμος': 'Municipality',
    'Χωριό' : 'Village',
    'Περιγραφή Χώρου' : 'Location Description',
    'Χαρακτηρισμός Συμβάντος' : 'Incident Characterization',
    'Σύνολο Πυρ. Οχημάτων' : 'Total Fire Vehicles',
    'Σύνολο Πυρ. Δυνάμεων (σε άνδρες και γυναίκες)' : 'Total Firefighting Personnel (men and women)',
    'Σύνολο Πυροσβεστικών Πλοιαρίων' : 'Total Fireboats',
    'Τύπος Ατυχήματος' : 'Accident Type',
    'Αριθμός εμπλεκομένων ανά τύπο ατυχήματος' : 'Number of Involved by Type',
    'Τραυματίες' : 'Injuries',
    'Θάνατοι' : 'Deaths',
    'Καταστροφές' : 'Damages',
    'Εγκαύματα' : 'Burns',
    'Σύνολο Πυροσβ. Πλοιαρίων' : 'Total Fireboats2',
    'Αριθμός εμπλεκομένων   ανά τύπο ' : 'Number of Involved by Type2'
}, inplace=True)

In [18]:
df.head()

,Record ID,Service,Region,Incident Type,Incident Start Date,Start Time,Extinguishing Date,Extinguishing Time,Municipality,Village,...,Total Firefighting Personnel (men and women),Total Fireboats,Accident Type,Number of Involved by Type,Injuries,Deaths,Damages,Burns,Total Fireboats2,Number of Involved by Type2
0,1165953,Π.Υ. Κ/Α ΑΘΗΝΩΝ - ΕΛΕΥΘ. ΒΕΝΙΖΕΛΟΣ,ΑΤΤΙΚΗΣ,ΠΥΡΚΑΓΙΑ,2014-01-04,19:36,NaN,NaN,Δ. ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ,NaN,...,3.0,NaN,NaN,1.0,0,0,0,0,NaN,NaN
1,1107604,Π.Υ. Κ/Α ΑΘΗΝΩΝ - ΕΛΕΥΘ. ΒΕΝΙΖΕΛΟΣ,ΑΤΤΙΚΗΣ,ΠΑΡΟΧΗ ΒΟΗΘΕΙΑΣ,2014-01-06,12:15,NaN,NaN,Δ. ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ,NaN,...,7.0,NaN,ΑΤΥΧΗΜΑ,2.0,2,0,0,0,NaN,NaN
2,1109979,Π.Υ. Κ/Α ΑΘΗΝΩΝ - ΕΛΕΥΘ. ΒΕΝΙΖΕΛΟΣ,ΑΤΤΙΚΗΣ,ΠΥΡΚΑΓΙΑ,2014-01-09,20:35,NaN,NaN,Δ. ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ,NaN,...,5.0,NaN,NaN,1.0,0,0,0,0,NaN,NaN
3,1107605,Π.Υ. Κ/Α ΑΘΗΝΩΝ - ΕΛΕΥΘ. ΒΕΝΙΖΕΛΟΣ,ΑΤΤΙΚΗΣ,ΠΥΡΚΑΓΙΑ,2014-01-18,13:47,NaN,NaN,Δ. ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ,NaN,...,4.0,NaN,NaN,1.0,0,0,0,0,NaN,NaN
4,1107607,Π.Υ. Κ/Α ΑΘΗΝΩΝ - ΕΛΕΥΘ. ΒΕΝΙΖΕΛΟΣ,ΑΤΤΙΚΗΣ,ΠΥΡΚΑΓΙΑ,2014-01-18,14:06,NaN,NaN,Δ. ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ,NaN,...,4.0,NaN,NaN,1.0,0,0,0,0,NaN,NaN

In [19]:
df.columns

Index(['Record ID', 'Service', 'Region', 'Incident Type',
       'Incident Start Date', 'Start Time', 'Extinguishing Date',
       'Extinguishing Time', 'Municipality', 'Village', 'Location Description',
       'Incident Characterization', 'Total Fire Vehicles',
       'Total Firefighting Personnel (men and women)', 'Total Fireboats',
       'Accident Type', 'Number of Involved by Type', 'Injuries', 'Deaths',
       'Damages', 'Burns', 'Total Fireboats2', 'Number of Involved by Type2'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 598930 entries, 0 to 65746
Data columns (total 23 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   Record ID                                     598930 non-null  int64
 1   Service                                       598930 non-null  object
 2   Region                                        598930 non-null  object
 3   Incident Type                                 598929 non-null  object
 4   Incident Start Date                           598930 non-null  object
 5   Start Time                                    598930 non-null  object
 6   Extinguishing Date                            117053 non-null  object
 7   Extinguishing Time                            116845 non-null  object
 8   Municipality                                  598930 non-null  object
 9   Village                                       221467 non-null  object
 10  Location Description                          598929 non-null  object
 11  Incident Characterization                     598930 non-null  object
 12  Total Fire Vehicles                           593255 non-null  float64
 13  Total Firefighting Personnel (men and women)  593274 non-null  float64
 14  Total Fireboats                               99431 non-null   float64
 15  Accident Type                                 75150 non-null   object
 16  Number of Involved by Type                    144871 non-null  float64
 17  Injuries                                      598930 non-null  int64
 18  Deaths                                        598930 non-null  int64
 19  Damages                                       598930 non-null  int64
 20  Burns                                         598930 non-null  int64
 21  Total Fireboats2                              454059 non-null  float64
 22  Number of Involved by Type2                   454059 non-null  float64
dtypes: float64(6), int64(5), object(12)
memory usage: 109.7+ MB

In [21]:
df.to_csv('data/en/final_data/resources_civil_data_2014_2024.csv', index=False)

In [22]:
print(df['Burns'].unique())
print(df['Injuries'].unique())
print(df['Damages'].unique())
print(df['Deaths'].unique())
print(df['Total Fireboats'].unique())
print(df['Total Fire Vehicles'].unique())
print(df['Total Firefighting Personnel (men and women)'].unique())

[ 0  2  1  3  4  6 15]
[ 0  2  1  5  3  4  6  8  7  9 72]
[0 1 3 4 2 6 7]
[ 0  1  2  3  4  5  7  6 55]
[nan  3.  5.  1.  4.  0.  2.  6. 20.  7. 42. 10.]
[  1.   3.   2.  nan   5.   7.   6.   4.  14.  21.  11.   0.  18.   9.
  13.  17.  10.   8.  15.  12.  26. 180.  20.  16.  30.  34.  25.  24.
  50.  60. 128. 328.  23.  19.  40. 111. 120.  22.  29.  80.  41.  64.
 160.  38.  28.  27.  44.  36.  78.  49.  31.  63. 103.  37.  32.  52.
  35.  33.  42.]
[3.000e+00 7.000e+00 5.000e+00 4.000e+00 8.000e+00       nan 1.000e+00
 1.400e+01 6.000e+00 2.000e+00 9.000e+00 1.300e+01 1.000e+01 1.200e+01
 1.600e+01 1.100e+01 1.500e+01 2.000e+01 2.300e+01 0.000e+00 3.000e+01
 1.900e+01 3.300e+01 1.800e+01 3.200e+01 1.700e+01 2.140e+02 3.600e+01
 3.500e+01 2.100e+01 2.400e+01 2.700e+01 2.800e+01 1.100e+02 3.900e+01
 4.100e+01 3.100e+02 2.500e+01 2.600e+01 5.200e+01 9.300e+01 6.200e+01
 2.200e+01 3.100e+01 4.800e+01 3.700e+01 6.400e+01 3.800e+01 2.200e+02
 5.300e+01 4.500e+01 4.000e+01 8.900e+01 4.300e+01 3.710e+02 7.000e+01
 3.460e+02 2.900e+01 3.400e+01 7.200e+01 8.100e+01 5.400e+02 4.200e+01
 5.600e+01 9.300e+02 6.100e+01 6.300e+01 5.000e+01 6.600e+01 8.000e+01
 7.100e+01 1.170e+02 4.840e+02 1.300e+02 6.262e+03 7.800e+01 9.120e+02
 5.400e+01 3.200e+02 2.820e+02 6.000e+01 9.700e+01 7.120e+02 5.500e+01
 3.150e+02 1.200e+02 8.300e+01 8.500e+01 4.400e+01 9.800e+01 6.720e+02
 6.800e+01 9.600e+01 6.900e+01 7.280e+02 8.200e+01 5.800e+01 7.400e+01
 1.870e+02 4.600e+01 4.500e+02 2.340e+02 2.300e+02 2.100e+02 1.220e+02
 2.400e+02 2.440e+02 4.900e+01 9.000e+01 8.700e+01 6.500e+01 2.160e+02
 4.700e+01 2.360e+02 1.897e+03 2.580e+02 4.350e+02 7.700e+01 5.100e+01
 7.500e+01 6.700e+01 3.398e+03 1.058e+03 2.500e+02 1.800e+02 5.700e+01
 1.150e+02 8.800e+01]

In [23]:
df['Incident Type'].unique()

array([' ΠΥΡΚΑΓΙΑ', ' ΠΑΡΟΧΗ ΒΟΗΘΕΙΑΣ', ' ΕΠΕΜΒΑΣΗ ΣΕ ΑΝΕΛΚΥΣΤΗΡΑ', nan,
       'Fire', 'Assistance Provision', 'ΕΠΕΜΒΑΣΗ ΣΕ ΑΝΕΛΚΥΣΤΗΡΑ',
       'Fire Report', 'ΔΕΛΤΙΟ ΠΑΡΟΧΗΣ ΒΟΗΘΕΙΑΣ',
       'ΔΕΛΤΙΟ ΕΠΕΜΒΑΣΗΣ ΣΕ ΑΝΕΛΚΥΣΤΗΡΑ', 'Assistance Provision Report'],
      dtype=object)

In [24]:
df_filtered = df.copy() 
df_filtered = df_filtered[df_filtered['Incident Type'].isin([' ΠΥΡΚΑΓΙΑ', 'Fire', 'Fire Report'])]  # interested only in fire events
df_filtered.drop(columns=['Record ID', 'Accident Type', 'Incident Type', 'Burns', 'Injuries', 'Damages', 'Deaths', 'Municipality', 'Village', 'Service'], inplace=True) 
# very few non-values or unneccessary columns

In [25]:
df_filtered

,Region,Incident Start Date,Start Time,Extinguishing Date,Extinguishing Time,Location Description,Incident Characterization,Total Fire Vehicles,Total Firefighting Personnel (men and women),Total Fireboats,Number of Involved by Type,Total Fireboats2,Number of Involved by Type2
0,ΑΤΤΙΚΗΣ,2014-01-04,19:36,NaN,NaN,ΑΙΘΟΥΣΕΣ ΑΝΑΜΟΝΗΣ ΕΠΙΒΑΤΩΝ,False Alarm,1.0,3.0,NaN,1.0,NaN,NaN
2,ΑΤΤΙΚΗΣ,2014-01-09,20:35,NaN,NaN,ΙΑΤΡΕΙΑ,False Alarm,1.0,5.0,NaN,1.0,NaN,NaN
3,ΑΤΤΙΚΗΣ,2014-01-18,13:47,NaN,NaN,ΚΑΤΑΣΤΗΜΑΤΑ,False Alarm,1.0,4.0,NaN,1.0,NaN,NaN
4,ΑΤΤΙΚΗΣ,2014-01-18,14:06,NaN,NaN,ΠΡΑΤΗΡΙΑ ΥΓΡΩΝ ΚΑΥΣΙΜΩΝ,False Alarm,1.0,4.0,NaN,1.0,NaN,NaN
5,ΑΤΤΙΚΗΣ,2014-01-25,01:00,NaN,NaN,ΕΜΠΟΡΙΚΑ ΚΕΝΤΡΑ,False Alarm,1.0,4.0,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65735,ΖΑΚΥΝΘΟΥ,2024-06-13,21:36,NaN,NaN,ΠΡΑΝΟΙ ΟΔΩΝ,Minor,1.0,2.0,NaN,NaN,0.0,1.0
65736,ΖΑΚΥΝΘΟΥ,2024-07-22,23:13,NaN,NaN,ΣΤΗΛΕΣ Δ.Ε.Η.,Minor,1.0,2.0,NaN,NaN,0.0,1.0
65738,ΖΑΚΥΝΘΟΥ,2024-08-14,18:14,NaN,NaN,ΠΡΑΝΟΙ ΟΔΩΝ,Minor,2.0,4.0,NaN,NaN,0.0,1.0
65739,ΖΑΚΥΝΘΟΥ,2024-08-27,21:10,NaN,NaN,ΟΙΚΟΠΕΔΙΚΟΙ ΧΩΡΟΙ,Minor,3.0,6.0,NaN,NaN,0.0,1.0
65743,ΖΑΚΥΝΘΟΥ,2024-10-15,13:31,NaN,NaN,ΜΕΤΑΦΟΡΙΚΑ ΜΕΣΑ ΞΗΡΑΣ,Minor,3.0,6.0,NaN,NaN,0.0,1.0

In [26]:
# merge columns Fireboats and Fireboats2
df_filtered['Total Fireboats'].fillna(df_filtered['Total Fireboats2'], inplace=True)
df_filtered.dropna(subset=['Total Fireboats', 'Total Fireboats2'], how='all', inplace=True)
df_filtered.drop(columns=['Total Fireboats2'], inplace=True)

C:\Users\Zosia\AppData\Local\Temp\ipykernel_6568\3435595793.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_filtered['Total Fireboats'].fillna(df_filtered['Total Fireboats2'], inplace=True)

In [27]:
df['Incident Characterization'].unique()

array(['False Alarm', 'Traffic Accidents', 'ΜΙΚΡΗ',
       'ΑΦΑΙΡΕΣΗ ΑΝΤΙΚΕΙΜΕΝΩΝ - ΚΑΤΑΡΡΕΥΣΕΙΣ',
       'ΑΠΕΛΕΥΘΕΡΩΣΗ ΑΠΟ ΑΝΕΛΚΥΣΤΗΡΑ', 'ΜΕΤΑΦΟΡΑ ΑΤΟΜΩΝ',
       'ΔΙΑΣΩΣΕΙΣ ΖΩΩΝ', 'ΔΙΑΦΥΓΗ ΕΠΙΚΙΝΔΥΝΩΝ ΟΥΣΙΩΝ', 'ΜΕΣΑΙΑ',
       'ΑΝΤΛΗΣΗ ΝΕΡΟΥ', 'ΑΝΟΙΓΜΑ ΘΥΡΩΝ', 'ΜΕΤΑΦΟΡΑ ΑΣΘΕΝΩΝ',
       'ΔΙΑΣΩΣΕΙΣ ΑΝΘΡΩΠΩΝ', 'ΠΛΥΣΙΜΟ ΟΔΟΥ', 'ΑΛΛΕΣ ΠΕΡΙΠΤΩΣΕΙΣ',
       'ΑΠΕΛΕΥΘΕΡΩΣΗ ΟΔΟΣΤΡΩΜΑΤΟΣ', 'ΜΕΓΑΛΗ', '-', 'ΑΝΕΥΡΕΣΗ ΑΓΝΟΟΥΜΕΝΟΥ',
       'ΠΛΗΡΩΣΗ ΔΕΞΑΜΕΝΩΝ', 'ΠΛΥΣΙΜΟ ΔΑΠΕΔΟΥ', 'ΡΙΨΗ ΠΡΙΟΝΙΔΙΟΥ',
       'ΕΡΓΑΤΙΚΑ ΑΤΥΧΗΜΑΤΑ', 'ΕΚΧΙΟΝΙΣΜΟΣ', 'ΠΛΥΣΙΜΟ ΣΤΕΓΗΣ',
       'Other Cases', 'ΤΡΟΧΑΙΑ ΑΤΥΧΗΜΑΤΑ', 'ΠΡΟΛΗΠΤΙΚΗ ΠΥΡΟΠΡΟΣΤΑΣΙΑ',
       'Minor', 'Major', 'ΨΕΥΔΗΣ ΑΝΑΓΓΕΛΙΑ', 'Medium',
       'Object Removal - Collapses'], dtype=object)

In [28]:
df_filtered = df_filtered[df_filtered['Incident Characterization'].isin(['False Alarm', 'ΜΙΚΡΗ', 'ΜΕΣΑΙΑ', 'Minor', 'Major', 'Medium', 'ΜΕΓΑΛΗ', 'ΨΕΥΔΗΣ ΑΝΑΓΓΕΛΙΑ', 'ΠΡΟΛΗΠΤΙΚΗ ΠΥΡΟΠΡΟΣΤΑΣΙΑ' ])] 
df_filtered['Incident Characterization'].replace({
    'ΜΙΚΡΗ': 'Minor',
    'ΜΕΣΑΙΑ': 'Medium',
    'ΜΕΓΑΛΗ': 'Major',
    'ΨΕΥΔΗΣ ΑΝΑΓΓΕΛΙΑ': 'False Alarm',
    'ΠΡΟΛΗΠΤΙΚΗ ΠΥΡΟΠΡΟΣΤΑΣΙΑ': 'Preventive Fire Protection'
}, inplace=True)

C:\Users\Zosia\AppData\Local\Temp\ipykernel_6568\1526281695.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_filtered['Incident Characterization'].replace({
C:\Users\Zosia\AppData\Local\Temp\ipykernel_6568\1526281695.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Incident Characterization'].replace({

In [29]:
df_filtered.dropna(subset=['Total Fire Vehicles', 'Total Firefighting Personnel (men and women)'], inplace=True)

C:\Users\Zosia\AppData\Local\Temp\ipykernel_6568\3080989582.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.dropna(subset=['Total Fire Vehicles', 'Total Firefighting Personnel (men and women)'], inplace=True)

In [30]:
print(df_filtered.isnull().sum())

Region                                               0
Incident Start Date                                  0
Start Time                                           0
Extinguishing Date                              180583
Extinguishing Time                              180938
Location Description                                 0
Incident Characterization                            0
Total Fire Vehicles                                  0
Total Firefighting Personnel (men and women)         0
Total Fireboats                                      0
Number of Involved by Type                      203157
Number of Involved by Type2                      43176
dtype: int64

In [31]:
# drop extinguishing date and time columns
extinguishing_date = pd.to_datetime(df_filtered['Extinguishing Date'], format='%d/%m/%Y', errors='coerce')
extinguishing_time = pd.to_datetime(df_filtered['Extinguishing Time'], format='%H:%M', errors='coerce')
df_filtered.drop(columns=['Extinguishing Date', 'Extinguishing Time'], inplace=True)
df_filtered.drop(columns=['Number of Involved by Type', 'Number of Involved by Type2'], inplace=True)

C:\Users\Zosia\AppData\Local\Temp\ipykernel_6568\1009668861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.drop(columns=['Extinguishing Date', 'Extinguishing Time'], inplace=True)
C:\Users\Zosia\AppData\Local\Temp\ipykernel_6568\1009668861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.drop(columns=['Number of Involved by Type', 'Number of Involved by Type2'], inplace=True)

In [32]:
df_translated = df_filtered.copy()

In [33]:
location_translations = {
    'ΠΛΟΙΑ': 'Ships',
    '----': 'Unknown/Not applicable',
    'ΣΤΑΘΜΟΙ ΠΑΡΑΓΩΓΗΣ ΕΝΕΡΓΕΙΑΣ': 'Energy Production Stations',
    'ΠΕΖΟΔΡΟΜΙΑ': 'Sidewalks',
    'ΚΤΙΡΙΑ ΔΙΑΜΕΡΙΣΜΑΤΩΝ': 'Apartment Buildings',
    'ΛΕΒΗΤΟΣΤΑΣΙΑ ΚΑΥΣΤΗΡΕΣ ΚΑΛΟΡΙΦΕΡ': 'Boiler Rooms',
    'ΘΕΑΤΡΑ': 'Theaters',
    'ΔΙΠΛΟΚΑΤΟΙΚΙΕΣ': 'Duplexes',
    'ΒΙΟΤΕΧΝΙΚΕΣ ΕΓΚΑΤΑΣΤΑΣΕΙΣ': 'Industrial Facilities',
    'ΣΤΑΥΛΟΙ': 'Stables',
    'ΧΩΡΟΙ ΑΝΑΨΥΧΗΣ (ΠΑΙΔ. ΧΑΡΕΣ)': 'Recreational Areas (Playgrounds)',
    'ΓΡΑΦΕΙΑ ΕΛΕΥΘΕΡΩΝ ΕΠΑΓΓΕΛΜΑΤΩΝ': 'Freelance Offices',
    'ΑΠΟΘΗΚΕΣ ΓΕΝΙΚΕΣ': 'General Warehouses',
    'ΧΩΡΟΙ ΑΘΛΗΤΙΚΩΝ ΣΥΓΚΕΝΤΡΩΣΕΩΝ': 'Sports Venues',
    'ΣΤΗΛΕΣ Δ.Ε.Η.': 'Public Power Corporation Poles',
    'ΕΣΤΙΑΤΟΡΙΑ': 'Restaurants',
    'ΜΕΤΑΦΟΡΙΚΑ ΜΕΣΑ ΘΑΛΑΣΣΗΣ': 'Maritime Transport Vehicles',
    'ΠΕΡΙΠΤΕΡΑ': 'Kiosks',
    'ΣΟΥΠΕΡ-ΜΑΡΚΕΤ': 'Supermarkets',
    'ΑΙΘΟΥΣΕΣ ΑΝΑΜΟΝΗΣ ΕΠΙΒΑΤΩΝ': 'Passenger Waiting Rooms',
    'ΓΡΑΦΕΙΑ ΕΠΙΧΕΙΡΗΣΕΩΝ': 'Business Offices',
    'ΞΕΝΟΔΟΧΕΙΑ': 'Hotels',
    'ΑΝΤΛΙΟΣΤΑΣΙΑ': 'Pumping Stations',
    'ΠΑΡΑΣΚΕΥΑΣΤΗΡΙΑ ΤΡΟΦΙΜΩΝ': 'Food Processing Plants',
    'ΕΜΠΟΡΙΚΑ ΚΕΝΤΡΑ': 'Shopping Centers',
    'ΧΩΡΟΙ ΕΚΘΕΣΕΩΝ': 'Exhibition Spaces',
    'ΔΗΜΟΤΙΚΕΣ ΤΟΥΑΛΕΤΕΣ': 'Public Toilets',
    'ΠΡΑΤΗΡΙΑ ΥΓΡΩΝ ΚΑΥΣΙΜΩΝ': 'Fuel Stations',
    'ΜΕΤΑΦΟΡΙΚΑ ΜΕΣΑ ΞΗΡΑΣ': 'Land Transport Vehicles',
    'ΚΑΤΑΣΤΗΜΑΤΑ': 'Shops',
    'ΑΕΡΟΔΡΟΜΙΑ': 'Airports',
    'ΤΗΛΕΠΙΚΟΙΝΩΝΙΑΚΕΣ ΕΓΚΑΤΑΣΤΑΣΕΙΣ': 'Telecommunications Facilities',
    'ΣΤΑΘΜΟΙ ΑΥΤΟΚΙΝΗΤΩΝ ΥΠΑΙΘΡΙΟΙ': 'Outdoor Car Stations',
    'ΟΡΓΑΝΩΜΕΝΑ ΠΛΥΝΤΗΡΙΑ': 'Organized Laundries',
    'ΣΥΝΕΡΓΕΙΑ ΣΥΝΤΗΡ.& ΕΠΙΣΚΕΥΗΣ ΑΥΤΟΚΙΝΗΤΩΝ': 'Car Maintenance & Repair Workshops',
    'ΑΛΣΗ': 'Groves',
    'ΟΙΚΟΔΟΜΕΣ': 'Construction Sites',
    'ΤΡΑΠΕΖΕΣ': 'Banks',
    'ΑΡΧΑΙΟΛΟΓΙΚΟΙ ΧΩΡΟΙ': 'Archaeological Sites',
    'ΝΕΚΡΟΤΑΦΕΙΑ': 'Cemeteries',
    'ΚΤΙΡΙΑ ΑΝΩΤΑΤΗΣ ΕΩΣ & ΔΗΜΟΤΙΚΗΣ ΕΚΠ/ΣΗΣ': 'Buildings of Higher to Municipal Education',
    'ΠΑΙΔΙΚΟΙ ΣΤΑΘΜΟΙ': 'Daycare Centers',
    'ΓΡΑΦΕΙΑ ΠΟΛΙΤΙΚΩΝ ΚΟΜΜΑΤΩΝ': 'Political Party Offices',
    'ΠΛΑΤΕΙΕΣ': 'Squares',
    'ΖΑΧΑΡΟΠΛΑΣΤΕΙΑ': 'Confectioneries',
    'ΓΡΑΦΕΙΑ ΔΗΜΟΣΙΩΝ ΥΠΗΡΕΣΙΩΝ': 'Public Service Offices',
    'ΣΤΑΘΜΟΙ ΑΥΤΟΚΙΝΗΤΩΝ ΣΤΕΓΑΣΜΕΝΟΙ': 'Indoor Car Stations',
    'ΝΟΣΟΚΟΜΕΙΑ': 'Hospitals',
    'ΜΟΥΣΕΙΑ': 'Museums',
    'ΔΙΑΧΩΡΙΣΤΙΚΗ ΝΗΣΙΔΑ ΟΔΩΝ': 'Road Medians',
    'ΚΕΝΤΡΑ ΔΙΑΣΚΕΔΑΣΗΣ': 'Entertainment Centers',
    'ΚΑΦΕΝΕΙΑ': 'Cafes',
    'ΚΟΥΡΕΙΑ - ΚΟΜΜΩΤΗΡΙΑ': 'Barber Shops - Hair Salons',
    'ΓΡΑΦΕΙΑ ΔΙΠΛΩΜΑΤΙΚΩΝ ΑΠΟΣΤΟΛΩΝ': 'Diplomatic Missions',
    'ΓΡΑΦΕΙΑ ΤΟΠΙΚΗΣ ΑΥΤΟΔΙΟΙΚΗΣΗΣ': 'Local Government Offices',
    'ΑΠΟΘΗΚΕΣ ΚΑΤΑΣΤΗΜΑΤΩΝ': 'Store Warehouses',
    'ΜΗΧΑΝΟΣΤΑΣΙΑ ΑΝΕΛΚΥΣΤΗΡΩΝ': 'Elevator Machinery Rooms',
    'ΙΝΣΤΙΤΟΥΤΑ': 'Institutes',
    'ΝΗΠΙΑΓΩΓΕΙΑ': 'Kindergartens',
    'ΦΑΡΜΑΚΕΙΑ': 'Pharmacies',
    'ΜΠΑΡ - ΚΑΦΕ': 'Bars - Coffee Shops',
    'ΝΑΟΙ': 'Temples',
    'ΙΑΤΡΕΙΑ': 'Clinics',
    'ΤΥΠΟΓΡΑΦΕΙΑ': 'Print Shops',
    'ΛΑΤΟΜΕΙΑ': 'Quarries',
    'ΤΡΑΙΝΑ': 'Trains',
    'ΑΓΟΡΕΣ ΚΑΙ ΥΠΕΡΑΓΟΡΕΣ': 'Markets and Supermarkets',
    'ΓΗΡΟΚΟΜΕΙΑ': 'Nursing Homes',
    'ΞΥΛΟΥΡΓΕΙΑ': 'Carpentries',
    'ΛΕΣΧΕΣ': 'Clubs',
    'ΜΟΤΟΠΟΔΗΛΑΤΑ': 'Motorcycles',
    'ΚΑΘΑΡΙΣΤΗΡΙΑ': 'Dry Cleaners',
    'ΘΑΛΑΣΣΙΟΣ ΧΩΡΟΣ': 'Maritime Area',
    'ΦΡΟΝΤΙΣΤΗΡΙΑ': 'Tutoring Centers',
    'ΘΕΡΜΟΚΗΠΙΑ': 'Greenhouses',
    'ΦΥΛΑΚΕΣ': 'Prisons',
    'ΧΩΡΟΙ ΣΥΝΕΔΡΙΩΝ': 'Conference Rooms',
    'ΓΕΩΡΓΙΚΗ ΕΚΤΑΣΗ': 'Agricultural Area',
    'ΑΓΡΟΤΙΚΕΣ ΠΕΡΙΟΧΕΣ': 'Rural Areas',
    'ΚΡΑΤΗΤΗΡΙΑ': 'Detention Centers',
    'ΑΠΟΘΗΚΕΣ ΑΓΡΟΤΙΚΕΣ': 'Agricultural Warehouses',
    'ΒΑΦΕΙΑ ΓΕΝΙΚΑ': 'General Dye Works',
    'ΟΙΚΟΤΡΟΦΕΙΑ-ΚΟΙΤΩΝΕΣ ΓΙΑ ΥΓΙΗ ΑΤ.> 6 ΕΤ.': 'Boarding Houses for Healthy Individuals > 6 Years',
    'ΑΝΑΜΟΡΦΩΤΗΡΙΑ': 'Reformatories',
    'ΑΥΤΟΚΙΝΟΥΜΕΝΑ ΜΗΧΑΝΗΜΑΤΑ': 'Self-propelled Machines',
    'ΕΡΓΟΤΑΞΙΑ': 'Construction Sites',
    'ΓΕΩΡΓΙΚΗ ΕΓΚΑΤΑΣΤΑΣΗ': 'Agricultural Facility',
    'ΕΚΣΚΑΠΤΙΚΑ - ΓΕΩΠΡΟΩΘΗΤΙΚΑ ΜΗΧ/ΤΑ': 'Excavation and Geotechnical Machines',
    'ΣΤΡΑΤΟΠΕΔΑ': 'Military Camps',
    'ΟΣΤΕΟΦΥΛΑΚΙΑ': 'Ossuaries',
    'ΦΟΥΡΝΟΙ ΟΙΚΙΩΝ': 'Home Ovens',
    'ΥΓΕΙΟΝΟΜΙΚΟΙ ΣΤΑΘΜΟΙ': 'Health Stations',
    'ΣΤΡΑΤΙΩΤΙΚΑ ΟΧΗΜΑΤΑ': 'Military Vehicles',
    'ΧΟΡΤΟΛΙΒΑΔΙΚΗ ΕΚΤΑΣΗ': 'Meadow Area',
    'ΔΑΣΗ': 'Forests',
    'ΨΥΧΙΑΤΡΕΙΑ': 'Psychiatric Hospitals',
    'ΕΡΓΑΣΤΗΡΙΑ ΕΡΕΥΝΩΝ & ΕΚΠΑΙΔΕΥΣΗΣ': 'Research and Education Laboratories',
    'ΙΔΡΥΜΑΤΑ ΑΝΙΑΤΩΝ ΑΤΟΜΩΝ': 'Institutions for the Disabled',
    'ΜΙΚΡΑ ΚΑΤ/ΜΑΤΑ ΕΠΙΔΙΟΡΘ. ΕΝΔΥΜ & ΥΠΟΔΗΜ.': 'Small Garment and Footwear Repair Shops',
    'ΛΙΜΕΝΙΚΑ ΥΠΟΣΤΕΓΑ': 'Port Shelters',
    'ΝΑΥΠΗΓΕΙΑ': 'Shipyards',
    'ΣΚΗΝΕΣ': 'Tents',
    'ΑΠΟΘΗΚΕΣ ΣΤΡΑΤΙΩΤΙΚΕΣ': 'Military Warehouses',
    'ΔΙΥΛΙΣΤΗΡΙΑ': 'Refineries',
    'ΟΙΚΟΙ ΑΝΟΧΗΣ': 'Brothels',
    'ΚΤΗΝΟΤΡΟΦΙΚΗ ΕΓΚΑΤΑΣΤΑΣΗ': 'Livestock Facility',
    'ΜΕΓΑΛΕΣ ΑΙΘΟΥΣΕΣ ΔΙΔΑΣΚΑΛΙΑΣ': 'Large Teaching Halls',
    'ΟΡΝΙΘΟΤΡΟΦΕΙΑ': 'Poultry Farms',
    'ΤΡΟΧΟΣΠΙΤΑ': 'Trailers',
    'ΑΡΤΟΠΟΙΕΙΑ': 'Bakeries',
    'ΓΕΩΡΓΙΚΑ ΜΗΧΑΝΗΜΑΤΑ': 'Agricultural Machinery',
    'ΚΑΛΑΜΙΑ-ΒΑΛΤΟΙ': 'Reed Beds',
    'ΞΕΝΩΝΕΣ': 'Guesthouses',
    'ΕΓΚΑΤΑΣΤΑΣΕΙΣ ΦΩΤΟΒΟΛΤΑΪΚΩΝ': 'Photovoltaic Installations',
    'ΚΙΝΗΜΑΤΟΓΡΑΦΟΙ': 'Cinemas',
    'ΛΕΜΒΟΙ': 'Boats',
    'ΠΟΔΗΛΑΤΑ': 'Bicycles',
    'ΑΝΥΨΩΤΙΚΑ ΜΗΧΑΝΗΜΑΤΑ': 'Lifting Machines',
    'ΧΟΙΡΟΤΡΟΦΕΙΑ': 'Pig Farms',
    'ΠΡΑΤΗΡΙΑ ΥΓΡΑΕΡΙΩΝ': 'Gas Stations',
    'ΒΟΥΣΤΑΣΙΑ': 'Cattle Farms',
    'ΑΜΦΙΘΕΑΤΡΑ': 'Amphitheaters',
    'ΚΛΙΝΙΚΕΣ': 'Clinics',
    'ΑΓΡΟΤΙΚΑ ΙΑΤΡΕΙΑ': 'Rural Clinics',
    'ΑΕΡΟΣΥΜΠΙΕΣΤΕΣ': 'Air Compressors',
    'ΒΙΒΛΙΟΘΗΚΕΣ': 'Libraries',
    'ΙΔΡΥΜΑΤΑ ΑΠΡΟΣΑΡΜΟΣΤΩΝ ΑΤΟΜΩΝ': 'Institutions for Unadapted Individuals',
    'ΕΡΓΑΣΤΗΡΙΑ ΣΥΝΤΗΡ.& ΕΠΙΣΚΕΥΗΣ ΜΟΤ/ΤΩΝ': 'Maintenance & Repair Workshops for Motor Vehicles',
    'ΑΕΡΟΠΛΑΝΑ': 'Airplanes',
    'ΣΦΑΓΕΙΑ': 'Slaughterhouses',
    'ΔΕΞΑΜΕΝΕΣ': 'Tanks',
    'ΑΛΥΚΕΣ': 'Salt Pans',
    'ΤΕΛΩΝΕΙΑ': 'Customs',
    'ΤΑΧΥΔΡΟΜΕΙΑ': 'Post Offices',
    'ΒΡΕΦΟΚΟΜΕΙΑ-ΒΡΕΦΟΝ. ΣΤΑΘΜΟΙ': 'Nurseries - Infant Stations',
    'ΞΥΛΙΝΕΣ ΓΕΦΥΡΕΣ': 'Wooden Bridges',
    'ΕΚΠΑΙΔΕΥΤΙΚΑ ΙΝΣΤΙΤΟΥΤΑ': 'Educational Institutes',
    'ΑΙΘΟΥΣΕΣ ΔΙΚΑΣΤΗΡΙΩΝ': 'Courtrooms',
    'ΑΠΟΘΗΚΕΣ ΜΟΥΣΕΙΩΝ': 'Museum Warehouses',
    'ΑΣΦΑΛΤΙΚΑ ΜΗΧΑΝΗΜΑΤΑ': 'Asphalt Machines',
    'ΙΧΘΥΟΤΡΟΦΕΙΑ': 'Fish Farms',
    'ΟΙΚΟΤΡΟΦΕΙΑ ΠΑΙΔΙΩΝ ΗΛΙΚΙΑΣ < 6 ΕΤΩΝ': 'Boarding Houses for Children Aged < 6 Years',
    'ΜΕΤΑΦΟΡΙΚΑ ΜΕΣΑ ΑΕΡΟΣ': 'Air Transport Vehicles',
    'ΣΠΗΛΑΙΟ': 'Cave',
    'ΣΙΔΕΡΩΤΗΡΙΑ': 'Ironing Rooms',
    'ΟΔΟΣ': 'Street',
    'ΜΟΝΟΚΑΤΟΙΚΙΕΣ': 'Detached houses',
    'ΠΡΑΝΟΙ ΟΔΩΝ': 'Road shoulders',
    'ΑΥΤΟΚΙΝΗΤΑ': 'Cars',
    'ΔΑΣΙΚΗ ΕΚΤΑΣΗ': 'Forest area',
    'ΧΩΡΟΙ ΑΠΟΡΡΙΜΑΤΩΝ': 'Waste disposal areas',
    'ΕΡΓΟΣΤΑΣΙΑ': 'Factories',
    'ΠΗΓΑΔΙ': 'Well',
    'ΑΚΑΤΟΙΚΗΤΑ ΟΙΚΗΜΑΤΑ': 'Uninhabited Buildings',
    'οικοπεδικοι χωροι': 'plots of land'
}

In [34]:
df_translated['Location Description'] = df_translated['Location Description'].str.strip().str.lower()
location_translations = {k.strip().lower(): v for k, v in location_translations.items()}
df_translated['Location Description'] = df_translated['Location Description'].replace(location_translations)

In [35]:
df_translated['Location Description'].unique()

array(['plots of land', 'street', 'road shoulders', 'Ships',
       'Unknown/Not applicable', 'Energy Production Stations',
       'Sidewalks', 'Apartment Buildings', 'detached houses',
       'Boiler Rooms', 'Theaters', 'Duplexes', 'Industrial Facilities',
       'Stables', 'Recreational Areas (Playgrounds)', 'cars',
       'Freelance Offices', 'General Warehouses', 'Sports Venues',
       'waste disposal areas', 'Public Power Corporation Poles',
       'Restaurants', 'Maritime Transport Vehicles', 'Kiosks',
       'Supermarkets', 'Passenger Waiting Rooms', 'Business Offices',
       'Hotels', 'Pumping Stations', 'Food Processing Plants',
       'Shopping Centers', 'Exhibition Spaces', 'Public Toilets',
       'Fuel Stations', 'Land Transport Vehicles', 'Shops', 'Airports',
       'Telecommunications Facilities', 'Outdoor Car Stations',
       'Organized Laundries', 'Car Maintenance & Repair Workshops',
       'Groves', 'Construction Sites', 'Banks', 'Archaeological Sites',
       'Cemeteries', 'Buildings of Higher to Municipal Education',
       'Daycare Centers', 'Political Party Offices', 'Squares',
       'Confectioneries', 'Public Service Offices', 'Indoor Car Stations',
       'Hospitals', 'Museums', 'Road Medians', 'Entertainment Centers',
       'Cafes', 'Barber Shops - Hair Salons', 'Diplomatic Missions',
       'Local Government Offices', 'Store Warehouses',
       'Elevator Machinery Rooms', 'Institutes', 'Kindergartens',
       'factories', 'Pharmacies', 'Bars - Coffee Shops', 'Temples',
       'Clinics', 'Print Shops', 'Quarries', 'Trains',
       'Markets and Supermarkets', 'Nursing Homes', 'forest area',
       'Carpentries', 'Clubs', 'Motorcycles', 'Dry Cleaners',
       'Maritime Area', 'Tutoring Centers', 'Greenhouses', 'Prisons',
       'Conference Rooms', 'Agricultural Area', 'Rural Areas',
       'Detention Centers', 'Agricultural Warehouses',
       'General Dye Works',
       'Boarding Houses for Healthy Individuals > 6 Years',
       'Reformatories', 'Self-propelled Machines',
       'Agricultural Facility', 'Excavation and Geotechnical Machines',
       'Military Camps', 'Ossuaries', 'Home Ovens', 'Health Stations',
       'Military Vehicles', 'Meadow Area', 'Forests',
       'Psychiatric Hospitals', 'Research and Education Laboratories',
       'Institutions for the Disabled',
       'Small Garment and Footwear Repair Shops', 'Port Shelters',
       'Shipyards', 'Tents', 'Military Warehouses', 'Refineries',
       'Brothels', 'Livestock Facility', 'Large Teaching Halls',
       'Poultry Farms', 'Trailers', 'Bakeries', 'Agricultural Machinery',
       'Reed Beds', 'Guesthouses', 'Photovoltaic Installations',
       'Cinemas', 'Boats', 'Bicycles', 'Lifting Machines', 'Pig Farms',
       'Gas Stations', 'Cattle Farms', 'Amphitheaters', 'Rural Clinics',
       'Air Compressors', 'Well', 'Libraries',
       'Institutions for Unadapted Individuals',
       'Maintenance & Repair Workshops for Motor Vehicles', 'Airplanes',
       'Slaughterhouses', 'Tanks', 'Salt Pans', 'Customs',
       'Uninhabited Buildings', 'Post Offices',
       'Nurseries - Infant Stations', 'Wooden Bridges',
       'Educational Institutes', 'Courtrooms', 'Museum Warehouses',
       'Asphalt Machines', 'Fish Farms',
       'Boarding Houses for Children Aged < 6 Years',
       'Air Transport Vehicles', 'Cave', 'Ironing Rooms', 'Street',
       'Detached houses', 'Road shoulders', 'Cars', 'Forest area',
       'Waste disposal areas', 'Factories'], dtype=object)

In [36]:
# Check for duplicates in unique values of "Location Description" and unify them
unique_values = df_translated['Location Description'].unique()
unified_mapping = {value.lower(): value for value in unique_values}  # Create a mapping with the preferred case
df_translated['Location Description'] = df_translated['Location Description'].str.lower().map(unified_mapping)
df_translated['Location Description'].unique()

array(['plots of land', 'Street', 'Road shoulders', 'Ships',
       'Unknown/Not applicable', 'Energy Production Stations',
       'Sidewalks', 'Apartment Buildings', 'Detached houses',
       'Boiler Rooms', 'Theaters', 'Duplexes', 'Industrial Facilities',
       'Stables', 'Recreational Areas (Playgrounds)', 'Cars',
       'Freelance Offices', 'General Warehouses', 'Sports Venues',
       'Waste disposal areas', 'Public Power Corporation Poles',
       'Restaurants', 'Maritime Transport Vehicles', 'Kiosks',
       'Supermarkets', 'Passenger Waiting Rooms', 'Business Offices',
       'Hotels', 'Pumping Stations', 'Food Processing Plants',
       'Shopping Centers', 'Exhibition Spaces', 'Public Toilets',
       'Fuel Stations', 'Land Transport Vehicles', 'Shops', 'Airports',
       'Telecommunications Facilities', 'Outdoor Car Stations',
       'Organized Laundries', 'Car Maintenance & Repair Workshops',
       'Groves', 'Construction Sites', 'Banks', 'Archaeological Sites',
       'Cemeteries', 'Buildings of Higher to Municipal Education',
       'Daycare Centers', 'Political Party Offices', 'Squares',
       'Confectioneries', 'Public Service Offices', 'Indoor Car Stations',
       'Hospitals', 'Museums', 'Road Medians', 'Entertainment Centers',
       'Cafes', 'Barber Shops - Hair Salons', 'Diplomatic Missions',
       'Local Government Offices', 'Store Warehouses',
       'Elevator Machinery Rooms', 'Institutes', 'Kindergartens',
       'Factories', 'Pharmacies', 'Bars - Coffee Shops', 'Temples',
       'Clinics', 'Print Shops', 'Quarries', 'Trains',
       'Markets and Supermarkets', 'Nursing Homes', 'Forest area',
       'Carpentries', 'Clubs', 'Motorcycles', 'Dry Cleaners',
       'Maritime Area', 'Tutoring Centers', 'Greenhouses', 'Prisons',
       'Conference Rooms', 'Agricultural Area', 'Rural Areas',
       'Detention Centers', 'Agricultural Warehouses',
       'General Dye Works',
       'Boarding Houses for Healthy Individuals > 6 Years',
       'Reformatories', 'Self-propelled Machines',
       'Agricultural Facility', 'Excavation and Geotechnical Machines',
       'Military Camps', 'Ossuaries', 'Home Ovens', 'Health Stations',
       'Military Vehicles', 'Meadow Area', 'Forests',
       'Psychiatric Hospitals', 'Research and Education Laboratories',
       'Institutions for the Disabled',
       'Small Garment and Footwear Repair Shops', 'Port Shelters',
       'Shipyards', 'Tents', 'Military Warehouses', 'Refineries',
       'Brothels', 'Livestock Facility', 'Large Teaching Halls',
       'Poultry Farms', 'Trailers', 'Bakeries', 'Agricultural Machinery',
       'Reed Beds', 'Guesthouses', 'Photovoltaic Installations',
       'Cinemas', 'Boats', 'Bicycles', 'Lifting Machines', 'Pig Farms',
       'Gas Stations', 'Cattle Farms', 'Amphitheaters', 'Rural Clinics',
       'Air Compressors', 'Well', 'Libraries',
       'Institutions for Unadapted Individuals',
       'Maintenance & Repair Workshops for Motor Vehicles', 'Airplanes',
       'Slaughterhouses', 'Tanks', 'Salt Pans', 'Customs',
       'Uninhabited Buildings', 'Post Offices',
       'Nurseries - Infant Stations', 'Wooden Bridges',
       'Educational Institutes', 'Courtrooms', 'Museum Warehouses',
       'Asphalt Machines', 'Fish Farms',
       'Boarding Houses for Children Aged < 6 Years',
       'Air Transport Vehicles', 'Cave', 'Ironing Rooms'], dtype=object)

In [37]:
df_transformed = df_translated.copy()

In [38]:
# create new features from Incident Start Date: Month, Day of the Week, Year
df_transformed['Year'] = pd.to_datetime(df_transformed['Incident Start Date']).dt.year
year_encoding = {year: idx for idx, year in enumerate(sorted(df_transformed['Year'].unique()))}
df_transformed['Year'] = df_transformed['Year'].map(year_encoding)
df_transformed['Month'] = pd.to_datetime(df_transformed['Incident Start Date']).dt.month
df_transformed['Day of the Week'] = pd.to_datetime(df_transformed['Incident Start Date']).dt.weekday

In [39]:
# create Hour from Start Time column
df_transformed['Hour'] = pd.to_datetime(df_transformed['Start Time'], format='%H:%M', errors='coerce').dt.hour

In [40]:
df_transformed.drop(columns=['Incident Start Date', 'Start Time'], inplace=True)

In [41]:
# encode Region, Location Description, Incident Characterization columns

region_encoding = {region: idx for idx, region in enumerate(df_transformed['Region'].unique())}
incident_characterization_encoding = {'Minor': 0, 'Medium': 1, 'Major': 2, 'False Alarm': 3, 'Preventive Fire Protection': 4}
description_encoding = {description: idx for idx, description in enumerate(df_transformed['Location Description'].unique())}

df_transformed['Region'] = df_transformed['Region'].map(region_encoding)
df_transformed['Incident Characterization'] = df_transformed['Incident Characterization'].map(incident_characterization_encoding)
df_transformed['Location Description'] = df_transformed['Location Description'].map(description_encoding)

print("Region Encoding:", region_encoding)
print("Incident Characterization Encoding:", incident_characterization_encoding)
print("Location Description Encoding:", description_encoding)

Region Encoding: {'ΑΤΤΙΚΗΣ': 0, 'ΘΕΣΣΑΛΟΝΙΚΗΣ': 1, 'ΗΜΑΘΙΑΣ': 2, 'ΑΧΑΙΑΣ': 3, 'ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ': 4, 'ΜΕΣΣΗΝΙΑΣ': 5, 'ΛΑΚΩΝΙΑΣ': 6, 'ΔΩΔΕΚΑΝΗΣΩΝ': 7, 'ΧΑΝΙΩΝ': 8, 'ΡΟΔΟΠΗΣ': 9, 'ΚΑΒΑΛΑΣ': 10, 'ΔΡΑΜΑΣ': 11, 'ΞΑΝΘΗΣ': 12, 'ΕΒΡΟΥ': 13, 'ΣΕΡΡΩΝ': 14, 'ΧΑΛΚΙΔΙΚΗΣ': 15, 'ΚΙΛΚΙΣ': 16, 'ΠΕΛΛΑΣ': 17, 'ΠΙΕΡΙΑΣ': 18, 'ΚΟΖΑΝΗΣ': 19, 'ΦΛΩΡΙΝΑΣ': 20, 'ΚΑΣΤΟΡΙΑΣ': 21, 'ΓΡΕΒΕΝΩΝ': 22, 'ΙΩΑΝΝΙΝΩΝ': 23, 'ΘΕΣΠΡΩΤΙΑΣ': 24, 'ΑΡΤΑΣ': 25, 'ΠΡΕΒΕΖΗΣ': 26, 'ΛΑΡΙΣΑΣ': 27, 'ΜΑΓΝΗΣΙΑΣ': 28, 'ΤΡΙΚΑΛΩΝ': 29, 'ΚΑΡΔΙΤΣΑΣ': 30, 'ΗΛΕΙΑΣ': 31, 'ΑΡΚΑΔΙΑΣ': 32, 'ΑΡΓΟΛΙΔΟΣ': 33, 'ΚΟΡΙΝΘΙΑΣ': 34, 'ΦΘΙΩΤΙΔΑΣ': 35, 'ΕΥΡΥΤΑΝΙΑΣ': 36, 'ΦΩΚΙΔΟΣ': 37, 'ΒΟΙΩΤΙΑΣ': 38, 'ΕΥΒΟΙΑΣ': 39, 'ΚΥΚΛΑΔΩΝ': 40, 'ΛΕΣΒΟΥ': 41, 'ΧΙΟΥ': 42, 'ΣΑΜΟΥ': 43, 'ΗΡΑΚΛΕΙΟΥ': 44, 'ΡΕΘΥΜΝΟΥ': 45, 'ΛΑΣΙΘΙΟΥ': 46, 'ΚΕΡΚΥΡΑΣ': 47, 'ΛΕΥΚΑΔΟΣ': 48, 'ΚΕΦΑΛΛΟΝΙΑΣ': 49, 'ΖΑΚΥΝΘΟΥ': 50, 'ΚΕΦΑΛΛΗΝΙΑΣ': 51}
Incident Characterization Encoding: {'Minor': 0, 'Medium': 1, 'Major': 2, 'False Alarm': 3, 'Preventive Fire Protection': 4}
Location Description Encoding: {'plots of land': 0, 'Street': 1, 'Road shoulders': 2, 'Ships': 3, 'Unknown/Not applicable': 4, 'Energy Production Stations': 5, 'Sidewalks': 6, 'Apartment Buildings': 7, 'Detached houses': 8, 'Boiler Rooms': 9, 'Theaters': 10, 'Duplexes': 11, 'Industrial Facilities': 12, 'Stables': 13, 'Recreational Areas (Playgrounds)': 14, 'Cars': 15, 'Freelance Offices': 16, 'General Warehouses': 17, 'Sports Venues': 18, 'Waste disposal areas': 19, 'Public Power Corporation Poles': 20, 'Restaurants': 21, 'Maritime Transport Vehicles': 22, 'Kiosks': 23, 'Supermarkets': 24, 'Passenger Waiting Rooms': 25, 'Business Offices': 26, 'Hotels': 27, 'Pumping Stations': 28, 'Food Processing Plants': 29, 'Shopping Centers': 30, 'Exhibition Spaces': 31, 'Public Toilets': 32, 'Fuel Stations': 33, 'Land Transport Vehicles': 34, 'Shops': 35, 'Airports': 36, 'Telecommunications Facilities': 37, 'Outdoor Car Stations': 38, 'Organized Laundries': 39, 'Car Maintenance & Repair Workshops': 40, 'Groves': 41, 'Construction Sites': 42, 'Banks': 43, 'Archaeological Sites': 44, 'Cemeteries': 45, 'Buildings of Higher to Municipal Education': 46, 'Daycare Centers': 47, 'Political Party Offices': 48, 'Squares': 49, 'Confectioneries': 50, 'Public Service Offices': 51, 'Indoor Car Stations': 52, 'Hospitals': 53, 'Museums': 54, 'Road Medians': 55, 'Entertainment Centers': 56, 'Cafes': 57, 'Barber Shops - Hair Salons': 58, 'Diplomatic Missions': 59, 'Local Government Offices': 60, 'Store Warehouses': 61, 'Elevator Machinery Rooms': 62, 'Institutes': 63, 'Kindergartens': 64, 'Factories': 65, 'Pharmacies': 66, 'Bars - Coffee Shops': 67, 'Temples': 68, 'Clinics': 69, 'Print Shops': 70, 'Quarries': 71, 'Trains': 72, 'Markets and Supermarkets': 73, 'Nursing Homes': 74, 'Forest area': 75, 'Carpentries': 76, 'Clubs': 77, 'Motorcycles': 78, 'Dry Cleaners': 79, 'Maritime Area': 80, 'Tutoring Centers': 81, 'Greenhouses': 82, 'Prisons': 83, 'Conference Rooms': 84, 'Agricultural Area': 85, 'Rural Areas': 86, 'Detention Centers': 87, 'Agricultural Warehouses': 88, 'General Dye Works': 89, 'Boarding Houses for Healthy Individuals > 6 Years': 90, 'Reformatories': 91, 'Self-propelled Machines': 92, 'Agricultural Facility': 93, 'Excavation and Geotechnical Machines': 94, 'Military Camps': 95, 'Ossuaries': 96, 'Home Ovens': 97, 'Health Stations': 98, 'Military Vehicles': 99, 'Meadow Area': 100, 'Forests': 101, 'Psychiatric Hospitals': 102, 'Research and Education Laboratories': 103, 'Institutions for the Disabled': 104, 'Small Garment and Footwear Repair Shops': 105, 'Port Shelters': 106, 'Shipyards': 107, 'Tents': 108, 'Military Warehouses': 109, 'Refineries': 110, 'Brothels': 111, 'Livestock Facility': 112, 'Large Teaching Halls': 113, 'Poultry Farms': 114, 'Trailers': 115, 'Bakeries': 116, 'Agricultural Machinery': 117, 'Reed Beds': 118, 'Guesthouses': 119, 'Photovoltaic Installations': 120, 'Cinemas': 121, 'Boats': 122, 'Bicycles': 123, 'Lifting Machines': 124, 'Pig Farms': 125, 'Gas Stations': 126, 'Cattle Farms': 127, 'Amphitheaters': 128, 'Rural Clinics': 129, 'Air Compressors': 130, 'Well': 131, 'Libraries': 132, 'Institutions for Unadapted Individuals': 133, 'Maintenance & Repair Workshops for Motor Vehicles': 134, 'Airplanes': 135, 'Slaughterhouses': 136, 'Tanks': 137, 'Salt Pans': 138, 'Customs': 139, 'Uninhabited Buildings': 140, 'Post Offices': 141, 'Nurseries - Infant Stations': 142, 'Wooden Bridges': 143, 'Educational Institutes': 144, 'Courtrooms': 145, 'Museum Warehouses': 146, 'Asphalt Machines': 147, 'Fish Farms': 148, 'Boarding Houses for Children Aged < 6 Years': 149, 'Air Transport Vehicles': 150, 'Cave': 151, 'Ironing Rooms': 152}

In [42]:
df_transformed.reset_index(drop=True, inplace=True)
df_transformed

,Region,Location Description,Incident Characterization,Total Fire Vehicles,Total Firefighting Personnel (men and women),Total Fireboats,Year,Month,Day of the Week,Hour
0,0,0,0,2.0,5.0,5.0,0,8,5,15
1,0,1,0,1.0,6.0,5.0,0,3,0,20
2,0,2,0,1.0,6.0,5.0,0,7,6,15
3,0,3,1,7.0,20.0,1.0,0,5,3,19
4,0,4,3,1.0,3.0,1.0,0,5,4,9
...,...,...,...,...,...,...,...,...,...,...
246328,50,2,0,1.0,2.0,0.0,10,6,3,21
246329,50,20,0,1.0,2.0,0.0,10,7,0,23
246330,50,2,0,2.0,4.0,0.0,10,8,2,18
246331,50,0,0,3.0,6.0,0.0,10,8,1,21
246332,50,34,0,3.0,6.0,0.0,10,10,1,13

In [43]:
df_transformed.rename(columns={'Total Firefighting Personnel (men and women)': 'Total Firefighting Personnel'}, inplace=True)

In [44]:
df_transformed.to_csv('df_ready.csv', index=False)